// adventure_creator/ui/src/app/layout.js
import './globals.css' // Keep or modify Next.js default global styles

export const metadata = {
  title: 'Adventure Map Creator',
  description: 'Generated by ADK and Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}